
skills_mapping = {
    
   'skill1' : {

    "AI": 0,
    "Ansible": 1,
    "Bioinformatics": 2,
    "C": 3,
    "C++": 4,
    "Cryptography": 5,
    "Cybersecurity": 6,
    "Dart": 7,
    "Data Science": 8,
    "Deep Learning": 9,
    "DevOps": 10,
    "Django": 11,
    "Docker": 12,
    "Elasticsearch": 13,
    "Embedded C": 14,
    "Ethical Hacking": 15,
    "FastAPI": 16,
    "Firebase": 17,
    "Fortran": 18,
    "Go": 19,
    "GraphQL": 20,
    "HBase": 21,
    "Java": 22,
    "JavaScript": 23,
    "Jenkins": 24,
    "Kafka": 25,
    "Kali Linux": 26,
    "Kubernetes": 27,
    "ML": 28,
    "Middleware": 29,
    "MongoDB": 30,
    "NLP": 31,
    "Neo4j": 32,
    "Node.js": 33,
    "NumPy": 34,
    "OpenCV": 35,
    "Power BI": 36,
    "PySpark": 37,
    "PyTorch": 38,
    "RTOS": 39,
    "RabbitMQ": 40,
    "React": 41,
    "Redux": 42,
    "Rust": 43,
    "SQL": 44,
    "Scala": 45,
    "Smart Contracts": 46,
    "Swift": 47,
    "Tableau": 48,
    "TensorFlow": 49,
    "TypeScript": 50,
    "Vue.js": 51
},

    
    'skill2': {
        
    "AI": 0,
    "Ansible": 1,
    "Bioinformatics": 2,
    "Blockchain": 3,
    "C": 4,
    "C++": 5,
    "Computer Vision": 6,
    "Cryptography": 7,
    "Cybersecurity": 8,
    "Data Science": 10,
    "Dart": 9,
    "Deep Learning": 11,
    "DevOps": 12,
    "Django": 13,
    "Docker": 14,
    "Elasticsearch": 15,
    "Embedded C": 16,
    "Ethical Hacking": 17,
    "FastAPI": 18,
    "Firebase": 19,
    "Flask": 20,
    "Flask-RESTful": 21,
    "Fortran": 22,
    "Go": 23,
    "GraphQL": 24,
    "Hadoop": 25,
    "HBase": 26,
    "Java": 26,
    "JavaScript": 27,
    "Jenkins": 28,
    "Julia": 29,
    "Kubernetes": 30,
    "Lisp": 31,
    "Metasploit": 33,
    "Middleware": 34,
    "ML": 32,
    "MongoDB": 35,
    "Next.js": 36,
    "Node.js": 37,
    "NumPy": 38,
    "OpenCV": 39,
    "Pandas": 40,
    "Perl": 41,
    "Power BI": 42,
    "Prolog": 43,
    "PySpark": 44,
    "RabbitMQ": 45,
    "React": 46,
    "Redux": 47,
    "RTOS": 45,
    "Rust": 49,
    "Scala": 48,
    "Smart Contracts": 52,
    "Spark": 53,
    "SQL": 50,
    "Swift": 54,
    "Tableau": 55,
    "TensorFlow": 56,
    "TypeScript": 51
},

    'skill3' : {
        
    "AWS": 0,
    "Ansible": 1,
    "Assembly": 2,
    "Bioinformatics": 3,
    "Blockchain": 4,
    "C": 5,
    "C++": 6,
    "CUDA": 7,
    "Cloud Computing": 8,
    "Cryptography": 9,
    "Cybersecurity": 10,
    "DevOps": 11,
    "Elasticsearch": 12,
    "Embedded C": 13,
    "Ethical Hacking": 14,
    "F#": 15,
    "FastAPI": 16,
    "Firebase": 17,
    "Flask": 18,
    "Flask-RESTful": 19,
    "Fortran": 20,
    "Go": 21,
    "HBase": 22,
    "Hadoop": 23,
    "IoT": 24,
    "Jenkins": 25,
    "Julia": 26,
    "Kafka": 27,
    "Kali Linux": 28,
    "Kubernetes": 29,
    "MATLAB": 30,
    "ML": 31,
    "Metasploit": 32,
    "Middleware": 33,
    "MongoDB": 34,
    "NLP": 35,
    "Neo4j": 36,
    "Next.js": 37,
    "NumPy": 38,
    "Penetration Testing": 39,
    "Prolog": 40,
    "PySpark": 41,
    "PyTorch": 42,
    "Python": 43,
    "RTOS": 44,
    "RabbitMQ": 45,
    "React": 46,
    "Redux": 47,
    "Smart Contracts": 48,
    "Solidity": 49,
    "Swift": 50,
    "Tableau": 51,
    "TensorFlow": 52,
    "TypeScript": 53
},

  'skill4':{
    
    "AI": 0,
    "Ansible": 1,
    "Assembly": 2,
    "Bioinformatics": 3,
    "Blockchain": 4,
    "C": 5,
    "C++": 6,
    "COBOL": 7,
    "CUDA": 8,
    "Cryptography": 9,
    "Dart": 10,
    "Data Science": 11,
    "DevOps": 12,
    "Django": 13,
    "Docker": 14,
    "Elasticsearch": 15,
    "FastAPI": 17,
    "F#": 16,
    "Firebase": 18,
    "Flask": 19,
    "Fortran": 20,
    "GraphQL": 21,
    "HBase": 22,
    "IoT": 23,
    "Java": 24,
    "JavaScript": 25,
    "Jenkins": 26,
    "Julia": 27,
    "Kali Linux": 28,
    "Kubernetes": 29,
    "MATLAB": 30,
    "Metasploit": 31,
    "MongoDB": 32,
    "NLP": 33,
    "Neo4j": 34,
    "Next.js": 35,
    "Node.js": 36,
    "NumPy": 37,
    "OpenCV": 38,
    "Pandas": 39,
    "Penetration Testing": 40,
    "Perl": 41,
    "Power BI": 42,
    "Prolog": 43,
    "PySpark": 44,
    "PyTorch": 45,
    "Python": 46,
    "RabbitMQ": 48,
    "React": 49,
    "Redux": 50,
    "RTOS": 47,
    "SQL": 51,
    "TensorFlow": 52,
    "TypeScript": 53,
    "Vue.js": 54
},

}

project_mapping = {
    
    0: "AI Virtual Assistant",
    1: "AI-Based Crime Prediction",
    2: "AI-Based Credit Score Prediction",
    3: "AI-Based Crop Disease Prediction",
    4: "AI-Based Customer Support",
    5: "AI-Based Fake News Detector",
    6: "AI-Based Fraud Detection",
    7: "AI-Based Game Opponent AI",
    8: "AI-Based Intelligent Tutoring System",
    9: "AI-Based Language Translator",
    10: "AI-Based Legal Document Summarization",
    11: "AI-Based Music Recommendation",
    12: "AI-Based Podcast Summarizer",
    13: "AI-Based Real-Time Emotion Detection",
    14: "AI-Based Virtual Personal Trainer",
    15: "AI-Generated Art System",
    16: "AI-Powered Automated Customer Feedback Analysis",
    17: "AI-Powered Code Review Assistant",
    18: "AI-Powered Content Moderation System",
    19: "AI-Powered Financial Fraud Detection",
    20: "AI-Powered Health Diagnosis",
    21: "AI-Powered Hiring System",
    22: "AI-Powered Legal Document Analysis",
    23: "AI-Powered Mental Health Chatbot",
    24: "AI-Powered Music Composition",
    25: "AI-Powered Personal Finance Advisor",
    26: "AI-Powered Resume Generator",
    27: "AI-Powered Virtual Shopping Assistant",
    28: "AI-Powered Wildlife Monitoring",
    29: "Automated Code Review System",
    30: "Automated Resume Screener",
    31: "Blockchain Voting System",
    32: "Cyber Threat Intelligence System",
    33: "Cybersecurity Threat Detector",
    34: "Disease Prediction System",
    35: "Drowsiness Detection System",
    36: "Face Recognition System",
    37: "Fake News Detection",
    38: "Hand Gesture Recognition",
    39: "Image Caption Generator",
    40: "IoT-Based Smart Farming",
    41: "Medical Image Analysis",
    42: "Reinforcement Learning Agent",
    43: "Self-Driving Car Simulation",
    44: "Sentiment Analysis",
    45: "Smart Surveillance System",
    46: "Smart Traffic Management System",
    47: "Social Media Sentiment Tracker",
    48: "Speech Emotion Recognition",
    49: "Stock Market Trend Analysis",
    50: "Stock Price Prediction",
    51: "Text Summarization Tool",


}